### PR TITLE
feat: add prometheus-stack (monitoring) capability

### PR DESCRIPTION
**Pull request by MxNxPx**
## Description

add prometheus-stack capability

## Related Issue

N/A

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Other (security config, docs update, etc)

## Checklist before merging

- [x] Test, docs, adr added or updated as needed
- [x] [Contributor Guide Steps](https://github.com/defenseunicorns/uds-template-capability/blob/main/CONTRIBUTING.md)(https://github.com/defenseunicorns/uds-template-capability/blob/main/CONTRIBUTING.md#submitting-a-pull-request) followed

### CODE REVIEW

**Review by jeff-mccoy — COMMENTED** [review]
can we leave the upstream images as the default (uncommented) until we have the `only.flavor` feature released next week in Zarf?

**Review by mikevanhemert — COMMENTED** [review]
inb4 @mjnagel does it make sense to call this capability `monitoring` instead of `prometheus` since it comes with alert manager and some other pieces in addition to Prometheus? A different alternative could be `prometheus-stack`

If it is changed, recommend updating the repository [`README.md`](https://github.com/defenseunicorns/uds-core#readme) to reflect the change

**Comment by mjnagel** [comment]
Yeah - I don't love calling it Prometheus since there is more included. I'm good with prometheus-stack or monitoring or other suggestions.

**Comment by MxNxPx** [comment]
> Yeah - I don't love calling it Prometheus since there is more included. I'm good with prometheus-stack or monitoring or other suggestions.

Fair point - my thought process here was that `monitoring` seemed too generic.  I'm more partial to `prometheus-stack` but am good with whatever @jeff-mccoy @mikevanhemert @mjnagel decide is the best name.

**Comment by mikevanhemert** [comment]
> > Yeah - I don't love calling it Prometheus since there is more included. I'm good with prometheus-stack or monitoring or other suggestions.
> 
> Fair point - my thought process here was that `monitoring` seemed too generic. I'm more partial to `prometheus-stack` but am good with whatever @jeff-mccoy @mikevanhemert @mjnagel decide is the best name.

If you like `prometheus-stack` then I think we have a winner @MxNxPx  🥳

**Comment by MxNxPx** [comment]
> can we leave the upstream images as the default (uncommented) until we have the `only.flavor` feature released next week in Zarf?

@jeff-mccoy - swapped it over now to use upstream.

**Review by jeff-mccoy — APPROVED** [review]

**Pull request merged**
