### PR TITLE
test: introduce new uds task file & ci structure

### PR DESCRIPTION
**Pull request by jeff-mccoy**
## Description

Utilize UDS CLI task runner for all local/remote jobs. This allows us to use the same commands locally or remotely. Also introducing per-capability and complete UDS Core testing in parallel, with fail-fast + custom runners for speed. 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Other (security config, docs update, etc)

## Checklist before merging

- [ ] Test, docs, adr added or updated as needed
- [ ] [Contributor Guide Steps](https://github.com/defenseunicorns/uds-template-capability/blob/main/CONTRIBUTING.md)(https://github.com/defenseunicorns/uds-template-capability/blob/main/CONTRIBUTING.md#submitting-a-pull-request) followed

### CODE REVIEW

**Comment by zachariahmiller** [comment]
Preliminary thought on this is that what you have in this pr right now is pretty much 100% tracking towards what i envisioned, only caveat being that there isn't a root level run task that can do all the things if you are doing local dev. 

That would be trivial to add in the future and would basically emulate the flow you have orchestrated in github workflows on local.

**Comment by zachariahmiller** [comment]
To your last commit message. You can do a fun bash one liner or use this https://github.com/philips-labs/list-folder-action and inline the filter instead of using the yaml file 🫠 

I thought the yaml file was the clearest option, albeit verbose

**Review by zachariahmiller — APPROVED** [review]
I don't really have much to say since I've been commenting on the progress along this journey... 🤣 LGTM! 🚀🦄

**Comment by jeff-mccoy** [comment]
lol yeah yaml wasn't bad really, just started feel like one more area for us to keep up with, but probably not that big of a deal

**Pull request merged**
