### PR TITLE
chore: conform to latest uds bundle schema

### PR DESCRIPTION
**Pull request by mikevanhemert**
## Description

...

## Related Issue

n/a

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Other (security config, docs update, etc)

## Checklist before merging

- [ ] Test, docs, adr added or updated as needed
- [ ] [Contributor Guide Steps](https://github.com/defenseunicorns/uds-template-capability/blob/main/CONTRIBUTING.md)(https://github.com/defenseunicorns/uds-template-capability/blob/main/CONTRIBUTING.md#submitting-a-pull-request) followed

### CODE REVIEW

**Review by zachariahmiller — DISMISSED** [review]
Assuming the checks pass LGTM.

**Review by mjnagel — DISMISSED** [review]
LGTM!

**Review by jeff-mccoy — CHANGES_REQUESTED** [review]
Think the example should change to use the env variables now (or at least ref them) in the main README. Also need to update `.vscode/settings.json`

**Comment by mikevanhemert** [comment]
> Think the example should change to use the env variables now (or at least ref them) in the main README. Also need to update `.vscode/settings.json`

Can you elaborate on using the env variables? Is there a way to set the version of UDS CLI with env variables?

The README and `.vscode/settings.json` have been updated

**Comment by jeff-mccoy** [comment]
Yeah it was added in this release: 

https://github.com/defenseunicorns/uds-cli/pull/220

**Review by zachariahmiller — DISMISSED** [review]
lgtm

**Review by mjnagel — APPROVED** [review]
:shipit:

**Review by jeff-mccoy — APPROVED** [review]

**Pull request merged**
